#!/usr/bin/python
import os

files = [".extra",".bash_profile",".bash_prompt",".exports",".aliases",".functions",".bashrc"]

print "!! Next action will replace following files !!"
for file in files:
	print "> ~/.%s" % (file, )

a = raw_input('\nDo you want to replace dotfiles? (y/n)\n')

if a.lower() == "y":
	for file in files:
		os.system("cp %s ~/" % (file, ))

	# copy bin files
	bin_files = ["server",]

	os.system("mkdir ~/.bin 2> /dev/null")
	for file in bin_files:
		os.system("cp .bin/%s ~/.bin" % (file,))

a = raw_input('\nDo you want to create gitconfig file? (y/n)\n')

if a.lower() == "y":
	email = raw_input('Enter your email address:\n')
	full_name = raw_input('Enter your full name:\n')

	schema_file = open(".gitconfig.schema", "r").read()
	schema_file = schema_file.replace("%EMAIL%", email)
	schema_file = schema_file.replace("%FULL_NAME%", full_name)
	with open(os.path.expanduser("~/.gitconfig"), "w") as f:
		f.write(schema_file)
		f.close()

a = raw_input('\nDo you want to install virtualenv (y/n)\n')

if a.lower() == "y":
	os.system("sudo easy_install pip")
	os.system("pip install --upgrade distribute")
	os.system("sudo pip install virtualenv")
	os.system("pip install virtualenvwrapper")

a = raw_input('\nDo you want to create ~/Projects and ~/Work dirs? (y/n)\n')

if a.lower() == "y":
	os.system("mkdir ~/Work 2> /dev/null")
	os.system("mkdir ~/Projects 2> /dev/null")

a = raw_input("\nDo you want to download iterm2 Solarized Dark style? (y/n)\n")

if a.lower() == "y":
	os.system("wget 'https://raw.github.com/altercation/solarized/master/iterm2-colors-solarized/Solarized%20Dark.itermcolors'")
	os.system("open 'Solarized Dark.itermcolors'")
	print "open iterm and set downloaded color sheme"

print "reload your console"
