#!/bin/bash
# source https://github.com/paulirish/dotfiles/blob/master/sync.sh
cd "$(dirname "$0")"
git pull
function sync_git() {
	rsync --exclude ".git/" --exclude ".DS_Store" --exclude "sync" --exclude "README.md" -av . ~
}
if [ "$1" == "--force" -o "$1" == "-f" ]; then
	sync_git
else
	read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1
	echo
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		sync_git
	fi
fi
unset sync_git
source ~/.bash_profile