#!/usr/bin/python
import SimpleHTTPServer, SocketServer, sys

map = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map
map[""] = "text/plain"

for key, value in map.items():
	map[key] = value + "charset=UTF-8"

class NoCacheHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):
	def do_GET(self, *args, **kwargs):
		self.headers["cache-control"] = "no-store, no-cache, must-revalidate, post-check=0, pre-check=0"
		self.headers["pragma"] = "no-cache"
		return SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET(self, *args, **kwargs)

httpd = SocketServer.TCPServer(("", int(sys.argv[1])), NoCacheHandler)
httpd.serve_forever()